title: Nariman Jafari # your name (or website title) here
logo: "/images/logo-1.png?raw=true" # your photo (or logo) here


description: > # your text below (remove <br> elements if you don't need line breaks)
  Welcome to my Data Analytics Portfolio Projects! This page showcases my skills in data analytics using Python, R, SQL, Excel, and Tableau. These beginner-friendly projects are designed to help me build a job-ready portfolio, with a focus on providing insights and solutions to real-world problems. This portfolio is intended for public viewing and potential employers. Take a look and let's connect!
  <br>
  <br>
  <a href="https://github.com/snowholt">View My GitHub Profile</a> 
  <br>
  <a href="https://public.tableau.com/app/profile/nariman.jafarieshlaghi">View My Tableau Vizzes</a> 
  <br>
  <a href="https://www.linkedin.com/in/narimanjafari/">View My LinkedIn Profile</a> 
  <br>
  <a href = "https://www.coursera.org/user/5bd1ee91041b267be3fa0c4a9e33d958" > View My Coursera Profile </a>
  <br>
  <br>
  
  <br>
remote_theme: pages-themes/minimal@v0.2.0
plugins: 
- jekyll-remote-theme

google_analytics: G-8W6DFV6J01 # your Google Analytics tracking ID here
